site:
  name: Amantle
  site: 'https://artyomnikolae7-sys.github.io'
  base: '/Amantle-Works.github.io'
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: Amantle
    template: '%s — Amantle'
  description: "Amantle — Ваше пространство для заметок, постов и идей. Создавайте, делитесь и вдохновляйтесь."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Amantle
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website

i18n:
  language: ru
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'system'
